[build]
  command = "pip install -r requirements.txt"
  functions = "api"

[functions]
  node_bundler = "none"
  included_files = ["api/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main/:splat"
  status = 200